SELECT TOP (1000) [full_name]
      ,[dob]
      ,[contact_no]
      ,[email]
      ,[state]
      ,[city]
      ,[pincode]
      ,[full_address]
      ,[user_id]
      ,[password]
      ,[account_status]
  FROM [C:\USERS\SAIRA\SOURCE\REPOS\MTAHA-21\CRESCENT-RDP\RDP\APP_DATA\RDP_DATABASE.MDF].[dbo].[member_master_tbl]